### ISSUE TITLE
Uninstalls and Reinstalls Docker when not Community Edition

### ISSUE THREAD

**Issue by Teagan42** [ajanis/ansible-docker#3]
# Issue

The removal of "old Docker versions" has hardcoded packages - including `docker.io` and `containerd`. These get removed, then the `Install Docker from OS Repo` task installs `docker_io_pkgs` which includes `docker.io` and `containerd`...

```yaml
- name: Install Docker from OS Repository
  block:
    - name: Remove old Docker versions
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent
    - name: Install Docker from OS Repo
      apt:
        name: "{{ docker_io_pkgs }}"
        update_cache: yes
        state: present
  when:
    - not docker_install_community_edition
```

```yaml
docker_io_pkgs:
  - docker.io
  - containerd
```

# Expected behavior

If `docker_install_community_edition` is not truthy - it should uninstall the community edition packages and install `docker_io_pkgs` leaving packages, if already installed, alone.
