### ISSUE TITLE
Nvidia installation tries to downgrade packages installed on previous run

### ISSUE THREAD

**Issue by Teagan42** [ajanis/ansible-docker#4]
# Issue
On installation of Nvidia packages specific versions are installed for `libnvidia-container-tools` and `libnvidia-container1` in task `install video driver for our card` but when `Install nvidia-docker2 and container runtime packages` task runs - it upgrades these packages since the `nvidia_docker_packages` does not specify versions of the binaries that use these packages. 

```yaml
nvidia_driver_packages:
  - nvidia-headless-460
  - libnvidia-encode-460
  - libnvidia-decode-460
#  - libnvidia-encode-460-server
#  - libnvidia-compute-460-server
  - libnvidia-container-tools=1.3.3-1
  - libnvidia-container1=1.3.3-1
#  - libnvidia-decode-460-server
  - nvidia-utils-460
  - nvidia-kernel-common-460
  - nvidia-kernel-source-460
#  - nvidia-driver-460

nvidia_docker_packages:
  - nvidia-container-toolkit
  - nvidia-docker2
  - nvidia-container-runtime
```

This works fine on the first run, but if you run it again, it tries to downgrade the `libnvidia-container-tools` and `libnvidia-container1` to the specified versions in `nvidia_driver_packages`:

```shell
TASK [docker : install video driver for our card] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [deepthought.home.prettybaked.com]: FAILED! => changed=false
  cache_update_time: 1622497397
  cache_updated: false
  msg: |-
    '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"      install 'libnvidia-container-tools=1.3.3-1' 'libnvidia-container1=1.3.3-1'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.
  rc: 100
  stderr: |-
    E: Packages were downgraded and -y was used without --allow-downgrades.
  stderr_lines: <omitted>
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following package was automatically installed and is no longer required:
      libavahi-client3
    Use 'apt autoremove' to remove it.
    The following packages will be REMOVED:
      nvidia-container-runtime nvidia-container-toolkit
    The following packages will be DOWNGRADED:
      libnvidia-container-tools libnvidia-container1
    0 upgraded, 0 newly installed, 2 downgraded, 2 to remove and 73 not upgraded.
  stdout_lines: <omitted>
```

# Expected behavior
Either use the versioned packages for the binaries or non-versioned libraries, this shouldn't happen.
